# Generated by Django 3.2 on 2021-06-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('language', models.CharField(max_length=50)),
                ('task_schedule', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
            ],
        ),
    ]
