# Generated by Django 3.2 on 2021-06-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='task_schedule',
            new_name='category',
        ),
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='todo',
            name='time',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
