# Generated by Django 3.2 on 2021-06-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210609_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='time',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
